### ISSUE TITLE
Provide ability to exclude test suites

### ISSUE THREAD

**Issue by Gert-dev** [twifty/atom-phpunit-integrator#14]
As PHPUnit runs all test suites by default, it is possible to exclude one or more from them via the `<groups><exclude><group>MyGroup</group></exclude></groups>` tags.

[PHP Integrator's core](https://gitlab.com/php-integrator/core/blob/development/phpunit.xml.dist) does this to avoid running the performance test suite by default, but to keep the unit and integration test suite running by default.

When running "all test suites", php-unit-integrator currently loops over the available ones and runs all of them, excluded or not.

I don't think it's necessary to actually read the PHPUnit file - you could do that nonetheless, of course. Instead, it may be easier to provide a "null" menu item in the list of suites that does not pass any suite arguments to PHPUnit, which would make it use its default behavior (and revert to what's specified in the XML). Setting this as default selection would apply the same behavior to this package as PHPUnit does via the command line.

Alternatively, you could make the suites dropdown a multiselect using checkboxes to toggle the ones you want.

**Comment by twifty** [comment]
I added the suite dropdown as a feature netbeans was missing. When building a large project (symfony for example) the core logic will be split into 'bundles'. Personally, I create a test suite for each bundle so I can narrow the test field as I develop. Removing the dropdown is not something I'm willing to do. A multi select would be a useful feature though.

Regarding the 'run all suites' feature, if I allow phpunit to run with default args (ie no testsuite on the command line) the package will have to wait for that process to complete before it can update the views. That could take several minutes on larger projects. This delay gives the impression that nothing is happening, especially when not looking at the terminal view output.

Test groups is a feature I've not implemented, simply because I have never used them and have no experience of how they work. But, it's probably something users would want.

I'll look into the phpunit source and see if I can mimic the exclusions in javascript.

**Comment by twifty** [comment]
Adding a method to abort the test(s) is next on my todo list. I'm currently adding a method to hide the terminal and coverage views within the tab.

The code could really benefit from using async generators, but they are not supported in atom yet.

**Comment by twifty** [comment]
v0.0.11 has a multi select for test suites and the ability to cancel running tests. I'll begin this issue of exclusions next.

**Comment by Gert-dev** [comment]
I realize I may have been confusing terms here, as PHP Integrator Core has a performance _suite_, but also marks those tests as the `Performance` _group_. In any case. I like the multiselect and it already seems to cover what I was looking for.

I'm not sure if this is a bug, but if I enable two of the three suites to run, they all do run successfully, but then the tests tree is cleared after both finished and I'm left with an empty pane. It completes the first suite, adds the tests to the tree, then completes the second suite, updates/replaces the tree with the output of the second suite and then finally clears all of the items from the tree. Is the intention perhaps to merge the results and show both?

**Comment by twifty** [comment]
It's supposed to merge all the results. The only thing cleared after each test is the terminal (for which I intend to track the history).

This is probably related to the new spinner I added.

**Comment by twifty** [comment]
Fixed in 0.0.14

Also to note, not selecting a test suite or group defaults to the normal phpunit behaviour.

**Comment by twifty** [comment]
0.0.15 now includes a terminal history. When running multiple files/suites, the terminal is written to with the output of the currently running or final test, erasing the old output. Now, clicking items in the tree from previously run suites/files will refresh the terminal with the output from that test.
