### ISSUE TITLE
Denote failed tests more clearly

### ISSUE THREAD

**Issue by Gert-dev** [twifty/atom-phpunit-integrator#31]
I've been using php-unit-integrator for a while now, and overall it's pretty much anything I'd expect of a test running package. :+1: 

Today, I was running tests and apparently I broke something (happens). However, whilst I did run the tests at a later point, I still didn't see that the tests were failing. The bottom bar lists the amount of failed tests, but it blends in with the rest of the panel. A button pops up to filter failed tests only when there are some to filter, but I didn't notice this change either. Finally, there were some failed tests in the tree, but they were listed further down, so they couldn't be seen without scrolling first.

Perhaps moving failed tests up top or providing some other overall obvious status on the top of the panel would be appropriate? This could be as simple as an obvious red message stating "Some tests failed" and a green text "All tests passing" otherwise.

What do you think? Or maybe I'm just not paying enough attention... :wink: .

**Comment by Gert-dev** [comment]
Sorting by test state seems do to the trick. thanks.

An alternative to using buttons would be to make the column headers clickable. If there is a separate column for the test state, you could sort by that to get test state sorting (and get errors pushed to the top), click the name to have alphabetical sorting and click the time column to see what the slowest/fastest test is. It'd reduce the amount of buttons and clickable column headers are fairly universal, I'd say.

Regarding the icons: I mentioned this already, but they look a bit out of place in Atom where most other packages use octicons, but I understand finding suitable ones may not be easy. The buttons are also rather fat compared to other buttons from the styleguide, which I'm presuming is due to the icons being used.

You mentioned previously that octicons doesn't provide the icons you're looking for. What icons are you referring to, specifically (maybe I can help)? I took the liberty of composing a small list of octicon alternatives to the current icons (listed in the Atom styleguide package) which seem appropriate:

* Run Suite: playback-fast-forward / gear / zap
* Stop Running: playback-pause / circle-slash
* Run Selected: playback-play
* Expand All: unfold / alignment-aligned-to
* Collapse All: fold / alignment-align
* Filter Passed / Succeeded Test: check
* Filter Skipped / Skipped Test: alert / issue-opened
* Filter Failed / Failed Test: circle-slash
* Toggle Terminal: terminal
* Toggle Coverage: graph

**Comment by twifty** [comment]
Headers like in the coverage panel table? That might work. I'm just worried about using too much real estate when the view is in the bottom dock. Maybe a popdown header on mouse hover would solve that problem.

I was thinking of doing something similar for the current 'expand' and 'sort' buttons. I don't like the way the filter buttons have been pushed out of view. This is a non-issue for the side docks though.

After looking at the icons available in the styleguide, there appears to be more than what I found on google. I'll have another look at your suggestions.

The button sizes are on my todo list. Even with using octicons, they are a little finicky to size and position the icon correctly. At the same time, the icon still needs to be visible. Even now, I'm using a 1440 display looking at a 14px font and can't see anything. I have bad eyes, that's why in one of the earlier versions you mentioned the font being too large.

**Comment by twifty** [comment]
0.0.32 includes a header bar, with sortable buttons, on the tree; Octicon icons; smaller buttons; context menu;
