### ISSUE TITLE
Idea - Only enable xdebug for code coverage or optionally

### ISSUE THREAD

**Issue by Gert-dev** [twifty/atom-phpunit-integrator#38]
An idea I had today was to only enable the xdebug extension conditionally.

As you probably know, just enabling the xdebug extension in php.ini causes [code to become considerably slower](https://github.com/nikic/PHP-Parser/blob/master/doc/component/Performance.markdown#xdebug), likely due to additional tracing happening in the background. For larger test suites, such as for PHP Integrator, this is a massive pain. To give an example: the default suite takes around 15 seconds without XDebug and around 40 seconds with XDebug loaded on my machine. (This is without code coverage being generated, of course.)

Usually I just disable the XDebug extension in my `php.ini` unless I need it for code coverage, but this quickly becomes tedious when I need to re-enable it to have code coverage once every so often. Because some people may want to have it enabled all the time - for smaller suites, it matters little -, an option to toggle it may be interesting.

There are some related possibilities here:
* Allow configuring additional command line arguments for PHP in the settings panel (currently you can only configure PHPUnit parameters and the PHP executable itself), which would allow one to add `-dzend_extension=xdebug.so` here if desired - but it does not solve the tediousness of toggling it on and off
* Allow configuring the command line arguments used for PHP _specifically_ when using code coverage, so one could add something like `-dzend_extension=xdebug.so` and keep it off in `php.ini`, which ensures it's only used for code coverage
* Add a toggle switch - much like the code coverage switch - that toggles whether xdebug is enabled, which in the background just adds `-dzend_extension=xdebug.so` - which would, again, probably need to be configurable, as the library name and/or path can differ per platform - when enabled and which is automatically force enabled by toggling the code coverage switch

There may be a better way to present this to the user. Unfortunately, there is no easier way to toggle XDebug, i.e. `xdebug_disable()` does not have the same effect and it _can_ be useful, such as for code coverage or just plain ol' debugging.

**Comment by twifty** [comment]
TBH, I didn't even realize it could be toggled on the command line.

Adding additional command lines for PHP is something which should be set across all projects. I don't like the idea of having to setup and configure each package that deals with PHP. I'd much prefer for all settings like 'php path', 'composer path', 'env variables' and the like to be set in one place. Ideally within your own `php-integrator-base` package. You've probably already noticed but, I first try to get the 'php path' from those configs and default to my own if not available. If you make those available in the base, I can easily import them. My other package `symfony-commands` also loads the base config.

I can, however, add a toggle switch for XDebug. It would only be clickable when coverage is disabled and always on when enabled. I could code it in such a way that it is only visible if a valid path to the extension is added to the config. I'm guessing most people who want it disabled have enough knowledge to find the correct path.

**Comment by Gert-dev** [comment]
I agree, which is why I started using project-manager for php-integrator-base and added an additional `php` key above the `php_integrator` key for each project; so that other packages may also place their own settings under it.

Unfortunately, the PHP executable or binary path is not currently part of the project settings, but it could easily be. If you want, you can just start reading out `php.binary` from the active project and use that as the binary. I could then also read that for use in php-integrator-base.

Though, before you do that, I noticed that Atom 1.26 has support for basic `.atomproject` files. I'm not sure how flexible these are, if these allow configuring package settings and if you can also have other "globalish" settings in there, such as a PHP binary path. That would allow us to do away with the dependency on project-manager; in fact, I've hoped for a long a time that Atom would provide some sort of project support out of the box, and hopefully this means it's finally coming.

In case you're interested: my idea was that any package could just request the current project's settings from an Atom service and plug in new project types to it, along with what settings apply for their project type (such as PHP), which could then be configured via an UI on top of that project manager.

**Comment by twifty** [comment]
Per project and per language settings is something atom has been missing. They were requested years ago, and only now they are starting to implement it? Well, if that's coming, I'll wait until 1.26 comes to my OS, then look into reading the config from there.

The dependencies on `php-integrator-base` are all contained within a single class. So, should the need arise, I can easily make it work with another library. I could even look into PHP parsers written in JS. I really only need class/method names and their line numbers.

**Comment by twifty** [comment]
Notable changes in 0.0.40:

A colon (':') separated list of PHP extensions can now be configured. When the Debug toggle is enabled, These extensions will be added to the command line using `-dzend_extension`. For this to work, and for the debug toggle to be visible, the xdebug extension needs commented from the php.ini file. Debug is enabled by default when code coverage is also enabled. I decided against using the `-n` flag and may implement finer control over the PHP process when a per-project configuration becomes available.

The package now uses [php-parser](https://github.com/glayzzle/php-parser) rather than `php-integrator-base`. This saves on having to filter methods declared within a classes parent scope; reduces the number of database (async) queries; negates having to wait for a database ready state; and negates having to hook the `reindexed` event.

As a result of the above changes, a few bugs are likely to arise :/

**Comment by Gert-dev** [comment]
Great! Finally no more fiddling with `xdebug.so` to accelerate the test suite.

A minor point of feedback may be to actually disable the `Debug` toggle and force it on if `Code Coverage` is toggled so it is immediately visible that one involves the other.

Another minor detail is that enabling `Debug` and/or `Code Coverage` will not work if the XDebug extension is not loaded. Disabling it if it isn't filled in in the settings may also make this clear to the user, but am I correct in thinking that you did not do this because this would force the user to disable XDebug first and not allow them to leave it always enabled?

Another idea to check for XDebug being loaded may be to use the PHP binary you already have to run something like `php -r "exit(function_exists('xdebug_disable') ? 1 : 0);"`. May be cheating, but hey, it works ;-).

Finally, I encountered this error when selecting a suite from the dropdown:

```
/home/user/.atom/packages/php-unit-integrator/lib/views/php-unit-integrator-view.js:683
Hide Stack Trace
TypeError: this.projectTester.setSelectedSuiteNames is not a function
    at PhpUnitIntegratorView.onSelectSuites (/home/user/.atom/packages/php-unit-integrator/lib/views/php-unit-integrator-view.js:683:28)
    at /home/user/.atom/packages/php-unit-integrator/node_modules/colletch/components/etch-multi-select.js:50:9
    at ViewRegistry.performDocumentUpdate (/usr/lib/atom/src/view-registry.js:238:7)
```

But overall, it works well!

**Comment by twifty** [comment]
Error fixed in 0.0.42

Style changes will be in the next patch

**Comment by Gert-dev** [comment]
Hiding it is probably better, indeed. I probably did not notice this because I was toggling XDebug in my php.ini without restarting Atom and not in the settings screen, which automatically hides/shows these toggles as appropriate.

**Comment by twifty** [comment]
HaHa. I thought about that when coding it. I need to a way to watch and reload settings which come from outside of atom, in this case the php.ini. Since that files location is dependent on the OS, and even then XDebug can be configured outside of that file, the only reliable way would be to invoke the process. That works for getting new values, not for watching changes. Eventually, I decided it was outside the scope of this package. However, the config should be reloaded any time the package settings change. I'll double check that is the case.

**Comment by twifty** [comment]
Debug toggle has been removed in 0.0.44. The code coverage toggle is visible only when XDebug is enabled in `php.ini` or a correct path to the extension is configured in the settings. I'd prefer not to show a disabled toggle when XDebug is not available since it conflicts with the toggles state when a test is running. I've updated the readme with a section pertaining to the code coverage settings.

**Comment by twifty** [comment]
I've been doing a little reading up on the `.atomproject` files. They appear to be targeted towards team devs as a method of sharing atom specific (mainly editor) settings across systems. Using it to store something like 'Path to PHP' wouldn't work since paths may very well be different on each system. Besides that, they are only loaded when launching atom from the command line with the `-p` argument.

It seems all my search results are targeted at either per language editor settings or sharing those settings between devs. I cannot find anything that resembles a single system configuration manager from which multiple packages can get/set values. I may have to create one myself :/

**Comment by Gert-dev** [comment]
Hmmm, that sounds rather unfortunate indeed. I am aware of [this pull request](https://github.com/atom/atom/pull/16698) that is still ongoing for Atom itself. Here's to hoping that that will be the solution to community packages.

**Comment by twifty** [comment]
@Gert-dev You may be interested in the [shared-settings](https://atom.io/packages/shared-settings) package.

It allows multiple packages to share settings under a common namespace. So for things like 'PHP Path', rather than the user setting it in each individual package, they can set it once within the main `Settings -> Shared` view. Our packages can then get/observe the 'shared.php' namespace.

All us devs need to do is add a dependency on the package, and configure a `sharedConfigSchema` in the `package.json` (or main module if going old school). It's in its early days and probably needs some tweaking of the mergeSchema methods, but it's a step towards a less confusing setting system.

**Comment by Gert-dev** [comment]
Looks good! A concern I have is that behind this configuration may lie additional logic that may then be shared as well (as an example, I recently added experimental Docker support to the php-integrator-base package, which needs to be executed differently than PHP from a binary), but I think that can be solved by actually exposing services again or making separate libraries that use these settings.

**Comment by Gert-dev** [comment]
Also, I wanted to mention [package-deps](https://github.com/steelbrain/package-deps) by steelbrain. If you decide you want to make installing another package required, you can use that to drop in the name of the packages you depend on and a popup will be displayed asking the user to install it if necessary.
